package interfaces;

import model.Dowod;

import java.util.List;

public interface DowodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.DOWOD
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer evidenceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.DOWOD
     *
     * @mbg.generated
     */
    int insert(Dowod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.DOWOD
     *
     * @mbg.generated
     */
    Dowod selectByPrimaryKey(Integer evidenceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.DOWOD
     *
     * @mbg.generated
     */
    List<Dowod> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.DOWOD
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Dowod record);
}