package interfaces;

import model.Oskarzony;

import java.util.List;

public interface OskarzonyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.OSKARZONY
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer criminalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.OSKARZONY
     *
     * @mbg.generated
     */
    int insert(Oskarzony record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.OSKARZONY
     *
     * @mbg.generated
     */
    Oskarzony selectByPrimaryKey(Integer criminalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.OSKARZONY
     *
     * @mbg.generated
     */
    List<Oskarzony> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.OSKARZONY
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Oskarzony record);
}