package interfaces;

import model.Pracownik;

import java.util.List;

public interface PracownikMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.PRACOWNIK
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.PRACOWNIK
     *
     * @mbg.generated
     */
    int insert(Pracownik record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.PRACOWNIK
     *
     * @mbg.generated
     */
    Pracownik selectByPrimaryKey(Integer cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.PRACOWNIK
     *
     * @mbg.generated
     */
    List<Pracownik> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.PRACOWNIK
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Pracownik record);
}