package interfaces;

import model.Sprawa;

import java.util.List;

public interface SprawaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.SPRAWA
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer lawsuitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.SPRAWA
     *
     * @mbg.generated
     */
    int insert(Sprawa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.SPRAWA
     *
     * @mbg.generated
     */
    Sprawa selectByPrimaryKey(Integer lawsuitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.SPRAWA
     *
     * @mbg.generated
     */
    List<Sprawa> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.SPRAWA
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Sprawa record);
}