package interfaces;

import model.Swiadek;

import java.util.List;

public interface SwiadekMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.SWIADEK
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer witnessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.SWIADEK
     *
     * @mbg.generated
     */
    int insert(Swiadek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.SWIADEK
     *
     * @mbg.generated
     */
    Swiadek selectByPrimaryKey(Integer witnessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.SWIADEK
     *
     * @mbg.generated
     */
    List<Swiadek> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.SWIADEK
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Swiadek record);
}