package interfaces;

import model.Wyrok;

import java.util.List;

public interface WyrokMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.WYROK
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer judgementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.WYROK
     *
     * @mbg.generated
     */
    int insert(Wyrok record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.WYROK
     *
     * @mbg.generated
     */
    Wyrok selectByPrimaryKey(Integer judgementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.WYROK
     *
     * @mbg.generated
     */
    List<Wyrok> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INF132340.WYROK
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Wyrok record);
}