package model;

import java.math.BigDecimal;

public class Dowod {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF132340.DOWOD.EVIDENCE_ID
     *
     * @mbg.generated
     */
    private Integer evidenceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF132340.DOWOD.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF132340.DOWOD.TYPE
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF132340.DOWOD.LAWSUIT_ID
     *
     * @mbg.generated
     */
    private BigDecimal lawsuitId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF132340.DOWOD.EVIDENCE_ID
     *
     * @return the value of INF132340.DOWOD.EVIDENCE_ID
     *
     * @mbg.generated
     */
    public Integer getEvidenceId() {
        return evidenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF132340.DOWOD.EVIDENCE_ID
     *
     * @param evidenceId the value for INF132340.DOWOD.EVIDENCE_ID
     *
     * @mbg.generated
     */
    public void setEvidenceId(Integer evidenceId) {
        this.evidenceId = evidenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF132340.DOWOD.NAME
     *
     * @return the value of INF132340.DOWOD.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF132340.DOWOD.NAME
     *
     * @param name the value for INF132340.DOWOD.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF132340.DOWOD.TYPE
     *
     * @return the value of INF132340.DOWOD.TYPE
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF132340.DOWOD.TYPE
     *
     * @param type the value for INF132340.DOWOD.TYPE
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF132340.DOWOD.LAWSUIT_ID
     *
     * @return the value of INF132340.DOWOD.LAWSUIT_ID
     *
     * @mbg.generated
     */
    public BigDecimal getLawsuitId() {
        return lawsuitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF132340.DOWOD.LAWSUIT_ID
     *
     * @param lawsuitId the value for INF132340.DOWOD.LAWSUIT_ID
     *
     * @mbg.generated
     */
    public void setLawsuitId(BigDecimal lawsuitId) {
        this.lawsuitId = lawsuitId;
    }
}