package model;

import java.math.BigDecimal;

public class Oskarzony {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF132340.OSKARZONY.CRIMINAL_ID
     *
     * @mbg.generated
     */
    private Integer criminalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF132340.OSKARZONY.CRIME_CATEGORY
     *
     * @mbg.generated
     */
    private String crimeCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF132340.OSKARZONY.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF132340.OSKARZONY.SURNAME
     *
     * @mbg.generated
     */
    private String surname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF132340.OSKARZONY.CODEX_ARTICLE
     *
     * @mbg.generated
     */
    private String codexArticle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF132340.OSKARZONY.PESEL
     *
     * @mbg.generated
     */
    private BigDecimal pesel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF132340.OSKARZONY.LAWSUIT_ID
     *
     * @mbg.generated
     */
    private BigDecimal lawsuitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF132340.OSKARZONY.OBRONCA_CARD_ID
     *
     * @mbg.generated
     */
    private Short obroncaCardId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF132340.OSKARZONY.CRIMINAL_ID
     *
     * @return the value of INF132340.OSKARZONY.CRIMINAL_ID
     *
     * @mbg.generated
     */
    public Integer getCriminalId() {
        return criminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF132340.OSKARZONY.CRIMINAL_ID
     *
     * @param criminalId the value for INF132340.OSKARZONY.CRIMINAL_ID
     *
     * @mbg.generated
     */
    public void setCriminalId(Integer criminalId) {
        this.criminalId = criminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF132340.OSKARZONY.CRIME_CATEGORY
     *
     * @return the value of INF132340.OSKARZONY.CRIME_CATEGORY
     *
     * @mbg.generated
     */
    public String getCrimeCategory() {
        return crimeCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF132340.OSKARZONY.CRIME_CATEGORY
     *
     * @param crimeCategory the value for INF132340.OSKARZONY.CRIME_CATEGORY
     *
     * @mbg.generated
     */
    public void setCrimeCategory(String crimeCategory) {
        this.crimeCategory = crimeCategory == null ? null : crimeCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF132340.OSKARZONY.NAME
     *
     * @return the value of INF132340.OSKARZONY.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF132340.OSKARZONY.NAME
     *
     * @param name the value for INF132340.OSKARZONY.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF132340.OSKARZONY.SURNAME
     *
     * @return the value of INF132340.OSKARZONY.SURNAME
     *
     * @mbg.generated
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF132340.OSKARZONY.SURNAME
     *
     * @param surname the value for INF132340.OSKARZONY.SURNAME
     *
     * @mbg.generated
     */
    public void setSurname(String surname) {
        this.surname = surname == null ? null : surname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF132340.OSKARZONY.CODEX_ARTICLE
     *
     * @return the value of INF132340.OSKARZONY.CODEX_ARTICLE
     *
     * @mbg.generated
     */
    public String getCodexArticle() {
        return codexArticle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF132340.OSKARZONY.CODEX_ARTICLE
     *
     * @param codexArticle the value for INF132340.OSKARZONY.CODEX_ARTICLE
     *
     * @mbg.generated
     */
    public void setCodexArticle(String codexArticle) {
        this.codexArticle = codexArticle == null ? null : codexArticle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF132340.OSKARZONY.PESEL
     *
     * @return the value of INF132340.OSKARZONY.PESEL
     *
     * @mbg.generated
     */
    public BigDecimal getPesel() {
        return pesel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF132340.OSKARZONY.PESEL
     *
     * @param pesel the value for INF132340.OSKARZONY.PESEL
     *
     * @mbg.generated
     */
    public void setPesel(BigDecimal pesel) {
        this.pesel = pesel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF132340.OSKARZONY.LAWSUIT_ID
     *
     * @return the value of INF132340.OSKARZONY.LAWSUIT_ID
     *
     * @mbg.generated
     */
    public BigDecimal getLawsuitId() {
        return lawsuitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF132340.OSKARZONY.LAWSUIT_ID
     *
     * @param lawsuitId the value for INF132340.OSKARZONY.LAWSUIT_ID
     *
     * @mbg.generated
     */
    public void setLawsuitId(BigDecimal lawsuitId) {
        this.lawsuitId = lawsuitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF132340.OSKARZONY.OBRONCA_CARD_ID
     *
     * @return the value of INF132340.OSKARZONY.OBRONCA_CARD_ID
     *
     * @mbg.generated
     */
    public Short getObroncaCardId() {
        return obroncaCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF132340.OSKARZONY.OBRONCA_CARD_ID
     *
     * @param obroncaCardId the value for INF132340.OSKARZONY.OBRONCA_CARD_ID
     *
     * @mbg.generated
     */
    public void setObroncaCardId(Short obroncaCardId) {
        this.obroncaCardId = obroncaCardId;
    }
}