package model;

import java.math.BigDecimal;

public class Wyrok {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF132340.WYROK.JUDGEMENT_ID
     *
     * @mbg.generated
     */
    private Integer judgementId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF132340.WYROK.CONTENT
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF132340.WYROK.JUDGEMENT
     *
     * @mbg.generated
     */
    private String judgement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF132340.WYROK.SUSPENCE
     *
     * @mbg.generated
     */
    private String suspence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INF132340.WYROK.LAWSUIT_ID
     *
     * @mbg.generated
     */
    private BigDecimal lawsuitId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF132340.WYROK.JUDGEMENT_ID
     *
     * @return the value of INF132340.WYROK.JUDGEMENT_ID
     *
     * @mbg.generated
     */
    public Integer getJudgementId() {
        return judgementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF132340.WYROK.JUDGEMENT_ID
     *
     * @param judgementId the value for INF132340.WYROK.JUDGEMENT_ID
     *
     * @mbg.generated
     */
    public void setJudgementId(Integer judgementId) {
        this.judgementId = judgementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF132340.WYROK.CONTENT
     *
     * @return the value of INF132340.WYROK.CONTENT
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF132340.WYROK.CONTENT
     *
     * @param content the value for INF132340.WYROK.CONTENT
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF132340.WYROK.JUDGEMENT
     *
     * @return the value of INF132340.WYROK.JUDGEMENT
     *
     * @mbg.generated
     */
    public String getJudgement() {
        return judgement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF132340.WYROK.JUDGEMENT
     *
     * @param judgement the value for INF132340.WYROK.JUDGEMENT
     *
     * @mbg.generated
     */
    public void setJudgement(String judgement) {
        this.judgement = judgement == null ? null : judgement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF132340.WYROK.SUSPENCE
     *
     * @return the value of INF132340.WYROK.SUSPENCE
     *
     * @mbg.generated
     */
    public String getSuspence() {
        return suspence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF132340.WYROK.SUSPENCE
     *
     * @param suspence the value for INF132340.WYROK.SUSPENCE
     *
     * @mbg.generated
     */
    public void setSuspence(String suspence) {
        this.suspence = suspence == null ? null : suspence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INF132340.WYROK.LAWSUIT_ID
     *
     * @return the value of INF132340.WYROK.LAWSUIT_ID
     *
     * @mbg.generated
     */
    public BigDecimal getLawsuitId() {
        return lawsuitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INF132340.WYROK.LAWSUIT_ID
     *
     * @param lawsuitId the value for INF132340.WYROK.LAWSUIT_ID
     *
     * @mbg.generated
     */
    public void setLawsuitId(BigDecimal lawsuitId) {
        this.lawsuitId = lawsuitId;
    }
}